Update Temp Daftar Aktivitas Page -> SearchController, UICollectionViewFolderCell, NavigationBarItem
gal-bert/nuro pull request #23
Opened 2022-10-14 02:19 UTC by finnchristoffer

2022-10-14 02:46 UTC, gal-bert commented on Nuro/Features/Parent/ActivityList/Controllers/ParentActivityListViewController+Delegate.swift
> +        let cell = parentActivityListView.tableViewFolder.dequeueReusableCell(withIdentifier: ParentActivityFolderTableViewCell.identifier) as! ParentActivityFolderTableViewCell
Kalo kata ko okta coba hindarin pake force unwrapping (!)

2022-10-14 02:47 UTC, gal-bert commented on Nuro/Features/Parent/ActivityList/ViewModels/ParentActivityListViewModel.swift
> +    func loadTableView() -> [String] {
Variable name nya coba diperjelas misal `loadDataToTableView`

2022-10-14 02:48 UTC, gal-bert commented on Nuro/Features/Parent/ActivityList/Views/ParentActivityListView.swift
> +    let scrollView: UIScrollView = {
Make variable `private lazy var`

2022-10-14 02:49 UTC, gal-bert commented on Nuro/Features/Parent/ActivityList/Views/ParentActivityListView.swift
> +    let tableViewFolder: UITableView = {
Should this be `private lazy var`?

2022-10-14 02:49 UTC, gal-bert commented on Nuro/Features/Parent/ActivityList/Views/ParentActivityListView.swift
> +    let stackView: UIStackView = {
Should this be `private lazy var`?

2022-10-14 02:50 UTC, gal-bert requested changes
Please check comments, overall LGTM

2022-10-14 04:16 UTC, steanox commented on Nuro/Utilities/Constants/CollectionViewAttributes.swift
> +    static let collectionViewFolderCellHeight = 256
Just make sure ini emang kalian mau pake sizenya static smua ya, kalo engga ya mngkin bs buat kalkulasi dsni kyak kemaren

2022-10-14 04:16 UTC, steanox reviewed
so far udah bgus sih nih udh lebih rapi dri kmren, great work ges !!

2022-10-14 04:42 UTC, finnchristoffer commented on Nuro/Features/Parent/ActivityList/Views/ParentActivityListView.swift
> +    let tableViewFolder: UITableView = {
tableview is public

2022-10-14 04:52 UTC, alliciaviona approved these changes
Looks good to me

2022-10-17 04:03 UTC, finnchristoffer commented on Nuro/Utilities/Constants/CollectionViewAttributes.swift
> +    static let collectionViewFolderCellHeight = 256
untuk bagian widthnya diubah ko jadinya karena pas dicoba di ipad mini gabisa kebagi 3 pas ada sidebarnya

2022-10-17 04:08 UTC, merged